### ISSUE TITLE
Correction: Hack the space Sundays

### ISSUE THREAD

**Issue by David-JA-Clarke** [NottingHack/members-guide#3]
usually the /first/ Sunday in the month, not the last.

**Comment by dpslwk** [comment]
which file is this in ?

**Comment by roberthunt** [comment]
https://github.com/NottingHack/members-guide/blob/efe9fdb2c6714d1aec2a076a13de7e9a2f073b1b/cleaning-improving.rst#hack-the-space-sundays

**Comment by dpslwk** [comment]
Fixed
