### ISSUE TITLE
Members boxes

### ISSUE THREAD

**Issue by alexmannuk** [NottingHack/members-guide#9]
The guide currently says that anyone paying over £10 a month can purchase a members box from us, but this requirement has never come up in any discussion I've had in person. Is this still a requirement?

**Comment by IanDickinson** [comment]
Hi Alex,

This used to be a rule sometime ago, but was dropped when the rules were 
redone.

i guess it's still appearing somewhere, but i can't see it one either of 
the following sites:

rules.nottinghack.org.uk
guide.nottinghack.org.uk

Regards,
Ian

**Comment by alexmannuk** [comment]
My mistake, it was on the wiki, not the members guide. Thanks for letting me know, I'll update it later today.
